name: brian2-binder
channels:
  - brian-team
  - conda-forge
dependencies:
  - python=3.6
  - pip=9.0*
  #- sphinx
  #- coverage
  - cython=0.27*
  - nose=1.3*
  - matplotlib=2.1*
  - brian2
  - brian2tools
